// Bakes audio/sfx/*.mp3 into js/sfxdata.js as base64, so the sound effects work
// with no server at all - opening index.html off the disk is a first-class way
// to run this game.
//
// Why this exists: the sampled cues are decoded into AudioBuffers so they can be
// trimmed, levelled, pitch-jittered and filtered (see js/audio.js). Getting the
// bytes for that needs fetch/XHR, and a file:// page is allowed neither, so the
// whole sample layer silently fell back to the old synth cues when the game was
// double-clicked instead of served. Inlining the bytes removes the network from
// the path entirely; js/audio.js still falls back to fetch for any file missing
// from here, so the two ways of running stay interchangeable.
//
//   node bake-sfx.js        # rerun after adding, removing or replacing a clip
//
// The MUSIC is deliberately NOT baked: it is ~70 MB, and an <audio> element
// streams a relative file:// path perfectly well - it was only ever fetch that
// was blocked.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'audio', 'sfx');
const OUT = path.join(__dirname, 'js', 'sfxdata.js');

const files = fs.readdirSync(SRC).filter((f) => /\.(mp3|ogg|wav)$/i.test(f)).sort();
if (!files.length) {
  console.error('no audio in ' + SRC);
  process.exit(1);
}

const lines = [
  '// GENERATED by bake-sfx.js - do not edit by hand.',
  '// audio/sfx/*.mp3 as base64, so the sampled cues need no server: a file://',
  '// page cannot fetch its own folder, and this is the whole reason the sounds',
  '// worked when served and did nothing when the page was opened off the disk.',
  '// Rerun `node bake-sfx.js` after any change to audio/sfx/.',
  'window.SFXDATA = {',
];

let raw = 0;
for (const f of files) {
  const buf = fs.readFileSync(path.join(SRC, f));
  raw += buf.length;
  // JSON.stringify the key: these filenames carry #, spaces, commas and quotes
  lines.push(JSON.stringify(f) + ':"' + buf.toString('base64') + '",');
}
lines.push('};', '');

const out = lines.join('\r\n');
fs.writeFileSync(OUT, out);
console.log('baked ' + files.length + ' files, '
  + (raw / 1024).toFixed(0) + ' KB -> ' + (out.length / 1024).toFixed(0) + ' KB at '
  + path.relative(__dirname, OUT));
